#theme: jekyll-theme-dinky
#remote_theme: carlosperate/jekyll-theme-rtd
remote_theme: rundocs/jekyll-rtd-theme

# Theme settings
repo_url: 'https://github.com/CBIIT/bento-docs'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
