# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bento-docs
tagline:          'Documentation for Bento-tools'
description:      'Documentation for Bento-tools: to setup bento data commons'
url:              https://CBIIT.github.io/bento-tools.io
baseurl:          /

author:
  name:           'Mark Benson'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CBIIT/bento-docs
